In [3]:
# numpy
!pip install numpy

In [4]:
# import numpy
import numpy as np

In [5]:
# cheking version of numpy
print(np.__version__)

1.26.4


In [6]:
#creating aaray
arr=np.array([10,20,30,40,50,60])
print(arr)

[10 20 30 40 50 60]


In [7]:
# cheking of array type
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
# tuple to create numpy array
arr=np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [9]:
# 0D Array
arr=np.array(12)
print(arr)

12


In [10]:
# 1D Array
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [11]:
# 2D Array
arr=np.array([[1,2,3,4,5],[60,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [60  7  8  9 10]]


In [12]:
# 3D Array
arr=np.array([[[3,4,5],[7,8,9]],[[1,2,3],[4,5,6]]])
print(arr)

[[[3 4 5]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
#cheak diamention of aaray
arr=np.array([[[3,4,5],[7,8,9]],[[1,2,3],[4,5,6]]])
print(arr.ndim)

3


In [14]:
#acess elements from 1D
arr=np.array([1,2,3,4,5,6])
print(arr[1])

2


In [15]:
#acess elements from 2D
arr=np.array([[1,2,3,4,5],[60,7,8,9,10]])
print(arr[0,3])

4


In [16]:
# negative indexes acesss
arr=np.array([[1,2,3,4,5],[60,7,8,9,10]])
print(arr[0,-2])


4


In [35]:
#array slicing
arr=np.array([2,4,6,8])
print(arr[arr%4==0])

[4 8]


In [18]:
#array slicing with step
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
print(arr[0:11:2])

[ 1  3  5  7  9 11]


In [36]:
#-ve index slicing
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
print(arr[1:3])

[2 3]


In [20]:
#cheching datatype array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
print(arr.dtype)

int32


In [21]:
#cheching shape of array
arr=np.array([[1,2,3,4,5],[60,7,8,9,10]])
print(arr.shape)

(2, 5)


In [22]:
#cheching size of elemnt
arr=np.array([[1,2,3,4,5],[60,7,8,9,10]])
print(arr.size)

10


In [23]:
#convrsion of datatype
arr=np.array([[1,2,3,4,5],[60,7,8,9,10]])
print(arr.astype(str))

[['1' '2' '3' '4' '5']
 ['60' '7' '8' '9' '10']]


In [24]:
#reshaping array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
#Iterating array elements
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [26]:
# joining array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)


[1 2 3 4 5 6]


In [27]:
#spliting of array
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)



[array([1, 2]), array([3, 4]), array([5, 6])]


In [28]:
# searching of index of an element
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [29]:
#sorting of array
#Ascending order
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
print(np.sort(arr))

#descending order
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
print(np.sort(arr)[::-1])

[ 1  2  3  4  5  6  7  8  9 10 11]
[11 10  9  8  7  6  5  4  3  2  1]


In [30]:
#Filtering array elements

arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [31]:
#adding and removing element
arr=np.array([1,2,3,4,5,6])

#Append
print(np.append(arr,[7,8]))

#insert
print(np.insert(arr,3,56))

#delete
print(np.delete(arr,[2]))


[1 2 3 4 5 6 7 8]
[ 1  2  3 56  4  5  6]
[1 2 4 5 6]


In [32]:
#Aggrigate function
a=np.array([10,20,30,40,50,60])

#sum
print(np.sum(a))

#min
print(np.min(a))

#max
print(np.max(a))

#cumulative sum
print(np.cumsum(a))

210
10
60
[ 10  30  60 100 150 210]


In [33]:
#ststical function
import statistics as stats
food_prices=([10,20,30,40,50,60,20,30])
a=np.array(food_prices)

#mean
print(np.mean(a))

#median
print(np.median(a))

#mode
print(stats.mode(a))

32.5
30.0
20


In [34]:
arr=np.array([5,10,15])
arr=arr*2
print(arr)

[10 20 30]
